### ISSUE TITLE
If layer is deleted, app breaks

### ISSUE THREAD

**Issue by driskull** [Esri/geoform-template-js#378]
Looks like this all doesnt have a valid layer. That breaks the app. We should handle this with a better error message.
 
http://audubon.maps.arcgis.com/apps/GeoForm/index.html?appid=00cf76c87d0545a78528e3cc0b9c2736&webmap=594f7f48c45246acbaa65a0ca50e9b82

```javascript
 TypeError: Cannot read property 'url' of null {stack: (...), message: "Cannot read property 'url' of null"} "TypeError: Cannot read property 'url' of null
    at null.<anonymous> (http://audubon.maps.arcgis.com/apps/GeoForm/js/main.js:125:36)
    at http://js.arcgis.com/3.12/init.js:177:296
    at Object.g.forEach (http://js.arcgis.com/3.12/init.js:229:285)
    at declare._createGeocoderOptions (http://audubon.maps.arcgis.com/apps/GeoForm/js/main.js:116:23)
    at declare._createGeocoderButton (http://audubon.maps.arcgis.com/apps/GeoForm/js/main.js:1902:32)
    at null.<anonymous> (http://audubon.maps.arcgis.com/apps/GeoForm/js/main.js:1397:22)
    at http://js.arcgis.com/3.12/init.js:177:296
    at c (http://js.arcgis.com/3.12/init.js:76:221)
    at d (http://js.arcgis.com/3.12/init.js:76:10)
    at resolve.callback (http://js.arcgis.com/3.12/init.js:77:350)"
```

**Comment by CTDisasterManagement** [comment]
@driskull,

If "this.config.form_layer.id" does not exist in web map layer collection then we  can simply show the message as "Layer does not exist" or "Please configure the layer".
Or you want any other error message.

Thanks!

**Comment by driskull** [comment]
How about both? "Form layer does not exist. Please configure the application and set the layer."

**Comment by CTDisasterManagement** [comment]
@driskull 

This is how error message will be shown if layer is deleted.
![image](https://cloud.githubusercontent.com/assets/5261405/5837763/ee3a65ec-a1a7-11e4-9d03-822409b18901.png)

The code is already merged in. 
Thanks
