### ISSUE TITLE
geoform on android device

### ISSUE THREAD

**Issue by driskull** [Esri/geoform-template-js#454]
alon.abramson says:
I’m having loading issues with the geoform on my android device. Have you run into this problem before? I’m unsure why this may happen, as the form is simply loading through an iframe. Would love some advice here.

http://blogs.esri.com/esri/arcgis/2014/09/25/the-geoform-graduates/#comment-7421

Need to test GeoForm through iframe on android device.

**Comment by amarinelli** [comment]
Experiencing the same issue on *Chrome (42.0.2311.111)*.  The result is just a perpetual loading screen.

While [Remote Dubugging Android with Chrome](https://developer.chrome.com/devtools/docs/remote-debugging) the console error message is:

```javascript
"ReferenceError: $ is not defined
    at declare._setAppConfigurations (http://ontarioregion.maps.arcgis.com/apps/GeoForm/js/main.js:1:12331)
    at null.<anonymous> (http://ontarioregion.maps.arcgis.com/apps/GeoForm/js/main.js:1:44427)
    at http://js.arcgis.com/3.13/init.js:4:16209
    at c (http://js.arcgis.com/3.13/init.js:2:13244)
    at d (http://js.arcgis.com/3.13/init.js:2:13033)
    at resolve.callback (http://js.arcgis.com/3.13/init.js:2:13875)
    at ia (http://js.arcgis.com/3.13/init.js:5:167874)
    at Pa (http://js.arcgis.com/3.13/init.js:5:168849)
    at oa (http://js.arcgis.com/3.13/init.js:5:168681)
    at http://js.arcgis.com/3.13/init.js:5:173375"
```

**Comment by driskull** [comment]
hmm. I'm having trouble installing chrome on my emulator. It does seem to work with the default android browser. I'll have to get my hand on a physical device to test.
