### ISSUE TITLE
TypeError:Cannot read property 'setAttribute' of null

### ISSUE THREAD

**Issue by bmwagehoft** [Esri/geoform-template-js#548]
I apologize if this isn't the right place for this, have been frustrated with my lack of knowledge in this area when working with the ESRI webapp templates.

After creating a GeoForm using the AGOL GeoForm Builder, the application fails to load and is returning the following:

TypeError: Cannot read property 'setAttribute' of null
    at Object.b.set (init.js:161)
    at Object._createFormElements (main.js:1126)
    at Object.<anonymous> (main.js:585)
    at init.js:63
    at Object.forEach (init.js:71)
    at Object._createForm (main.js:564)
    at Object.<anonymous> (main.js:1567)
    at init.js:63
    at c (init.js:103)
    at d (init.js:103) "TypeError: Cannot read property 'setAttribute' of null
    at Object.b.set (https://js.arcgis.com/3.23/init.js:161:49)
    at Object._createFormElements (http://msi.maps.arcgis.com/apps/GeoForm/js/main.js:1126:17)
    at Object.<anonymous> (http://msi.maps.arcgis.com/apps/GeoForm/js/main.js:585:14)
    at https://js.arcgis.com/3.23/init.js:63:337
    at Object.forEach (https://js.arcgis.com/3.23/init.js:71:19)
    at Object._createForm (http://msi.maps.arcgis.com/apps/GeoForm/js/main.js:564:13)
    at Object.<anonymous> (http://msi.maps.arcgis.com/apps/GeoForm/js/main.js:1567:18)
    at https://js.arcgis.com/3.23/init.js:63:337
    at c (https://js.arcgis.com/3.23/init.js:103:393)
    at d (https://js.arcgis.com/3.23/init.js:103:182)"

I am trying to build a GeoForm that will allow users to digitize logs of water main break locations into a point dataset. I have pointed the geoform to a hosted feature layer with several fields. Several of the fields have coded domains and all fields allow NULL values. I have a feature template setup with default field entries based on my domains.

Any help with this issue would be appreciated. 

Thanks.

**Comment by driskull** [comment]
Did you figure it out @bmwagehoft?

**Comment by bmwagehoft** [comment]
ESRI Support and I narrowed it down to a field in my hosted feature layer having a DATE field type. After disabling that field my GeoForm loads perfectly. I believe another user had this error recently, #524. Not sure if a solution was ever arrived at, but for now I will just forgo using that specific field. Thanks @driskull.

**Comment by driskull** [comment]
cool. thanks. Just wanted to make sure everything is good.
